---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: install pip module
      pip:
        name: docker
        state: present

    - name: check if bootstrap still works.
      include_role:
        name: robertdebock.bootstrap

    - name: remove pip module
      pip:
        name: docker
        state: absent

    - name: check if requested modules can be installed
      include_role:
        name: ansible-role-python_pip
      vars:
        python_pip_modules:
          - name: docker
