---
# defaults file for python_pip

# The version of pip to update to.
python_pip_version: 19.0.1

# By default no modules should be installed.
python_pip_modules: []

# To update all packages installed by this roles, set `python-pip_package_state` to `latest`.
python_pip_package_state: present
