---
galaxy_info:
  author: Robert de Bock
  role_name: vagrant
  description: Install vagrant on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Fedora
      versions:
        - 31
        - 32
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - bionic
        - xenial

  galaxy_tags:
    - vagrant
    - centos

dependencies: []
