---
galaxy_info:
  author: Robert de Bock
  namespace: robertdebock
  role_name: travis
  description: Installs travis on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: "2.10"

  platforms:
    - name: Alpine
      versions:
        - all
    - name: EL
      versions:
        - 8
    - name: Debian
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - travis

dependencies: []
