---
- src: robertdebock.ansible
  name: ansible
- src: robertdebock.ansible_lint
  name: ansible_lint
- src: robertdebock.ara
  name: ara
- src: robertdebock.atom
  name: atom
- src: robertdebock.bootstrap
  name: bootstrap
- src: robertdebock.buildtools
  name: buildtools
- src: robertdebock.common
  name: common
- src: robertdebock.docker
  name: docker
- src: robertdebock.epel
  name: epel
- src: robertdebock.fail2ban
  name: fail2ban
- src: robertdebock.git
  name: git
- src: robertdebock.investigate
  name: investigate
- src: robertdebock.molecule
  name: molecule
- src: robertdebock.postfix
  name: postfix
- src: robertdebock.python_pip
  name: python_pip
- src: robertdebock.reboot
  name: reboot
- src: robertdebock.ruby
  name: ruby
- src: robertdebock.service
  name: robertdebock.service
- src: robertdebock.travis
  name: travis
- src: robertdebock.update
  name: update
- src: robertdebock.users
  name: users
- src: robertdebock.vagrant
  name: vagrant
