---
galaxy_info:
  author: Robert de Bock
  role_name: ara
  description: Install and configure ara on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 8
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Fedora
      versions:
        - 31
        - 32
    - name: Ubuntu
      versions:
        - bionic

  galaxy_tags:
    - ansiblerecordsansible
    - ara
    - arareportsansible
    - cloud
    - centos
    - development
    - monitoring
    - reporting

dependencies: []
