---
# vars file for buildroot
_buildtools_packages:
  default:
    - build-essential
  Alpine:
    - alpine-sdk
    - libffi-dev
    - openssl-dev
    - perl-utils
  Amazon:
    - gcc
    - make
  Archlinux:
    - base-devel
  CentOS:
    - "@Development tools"
    - perl-Digest-SHA
  Fedora:
    - "@Development tools"
    - perl-Digest-SHA
  openSUSE Leap:
    - autoconf
    - automake
    - binutils
    - bison
    - cpp
    - cvs
    - flex
    - gcc
    - gdbm-devel
    - gettext-tools
    - glibc-devel
    - libtool
    - m4
    - make
    - makeinfo
    - patch
    - zlib-devel
    - bin86
    - binutils-devel
    - fdupes
    - gcc-c++
    - gcc-info
    - glibc-info
    - gmp-devel
    - gperf
    - libaio-devel
    - libapparmor-devel
    - libdb-4_8-devel
    - libgcj-devel
    - libosip2-devel
    - libstdc++-devel
    - openldap2-devel
    - pam-devel
    - patch
    - pkg-config
    - subversion
  openSUSE Tumbleweed:
    - autoconf
    - automake
    - binutils
    - bison
    - cpp
    - cvs
    - flex
    - gcc
    - gdbm-devel
    - gettext-tools
    - glibc-devel
    - libtool
    - m4
    - make
    - makeinfo
    - patch
    - zlib-devel
    - bin86
    - binutils-devel
    - fdupes
    - gcc-c++
    - gcc-info
    - glibc-info
    - gmp-devel
    - gperf
    - libaio-devel
    - libapparmor-devel
    - libdb-4_8-devel
    - libosip2-devel
    - libstdc++-devel
    - openldap2-devel
    - pam-devel
    - patch
    - pkg-config
    - subversion

buildtools_packages: "{{ _buildtools_packages[ansible_distribution] | default (_buildtools_packages['default'] ) }}"
