---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: python_pip-debian
    box: debian/stretch64
  - name: python_pip-fedora
    box: fedora/30-cloud-base
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      python_pip-fedora:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: vagrant
