---
galaxy_info:
  author: Robert de Bock
  namespace: robertdebock
  role_name: service
  description: Add custom services to your Linux system.
  license: Apache-2.0
  company: none
  min_ansible_version: "2.10"

  platforms:
    - name: EL
      versions:
        - 8
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - service

dependencies: []
