---
galaxy_info:
  author: Robert de Bock
  role_name: service
  description: Add custom services to your Linux system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.8

  platforms:
    - name: Amazon
      versions:
        - all
    - name: Alpine
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - artful
        - bionic

  galaxy_tags:
    - service
    - archlinux
    - centos
    - redhat

dependencies: []
