---
# defaults file for git

# The system username in /home where to place the gitconfig file.
git_username: johndoe

# The group to own directories.
git_groupname: "{{ git_username }}"

# Settings for git configuration.
git_user_email: johndoe@example.com
git_user_name: John Doe

# Where to place the copies of the repositories.
git_repository_destination: /home/{{ git_username }}/Documents/github.com/{{ git_username }}

# The repositories to check out, bootstrap is pinned to a version, java will get HEAD/latest.
# git_repositories:
#   - repo: https://github.com/robertdebock/ansible-role-bootstrap.git
#     dest: bootstrap
#     version: 2.2.4
#   - repo: ssh://git@github.com/robertdebock/ansible-role-java.git
#     dest: java

# To update packages this role places on the system, set `git_package_state` to `latest`.
git_package_state: present

# Some Docker containers do not allow managing services, rebooting and writing
# to some locations in /etc. The role skips tasks that will typically fail in
# Docker. With this parameter you can tell the role to -not- skip these tasks.
git_ignore_docker: yes
