---

- name: test if update_autoremove is set correctly
  ansible.builtin.assert:
    that:
      - update_autoremove is defined
      - update_autoremove is boolean
    quiet: yes

- name: test if update_upgrade_command is set correctly
  ansible.builtin.assert:
    that:
      - update_upgrade_command is defined
      - update_upgrade_command is string
      - update_upgrade_command in [ "dist", "full", "yes", "safe" ]
    quiet: yes

- name: test if update_cache_valid_time is set correctly
  ansible.builtin.assert:
    that:
      - update_cache_valid_time is defined
      - update_cache_valid_time is number
      - update_cache_valid_time >= 0
    quiet: yes

- name: test if update_reboot is set correctly
  ansible.builtin.assert:
    that:
      - update_reboot is defined
      - update_reboot is boolean
    quiet: yes
