---
galaxy_info:
  author: Robert de Bock
  role_name: digitalocean_agent
  description: Install digitalocean agent on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.6

  platforms:
    - name: EL
      version:
        - 6
        - 7
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - digitalocean
    - digitaloceanagent
    - doagent
    - centos
    - fedora
    - rhel

dependencies: []
