---
# tasks file for python_pip
- name: install python pip
  package:
    name: "{{ python_pip_packages }}"
    state: present
  register: python_pip_install_python_pip
  until: python_pip_install_python_pip is succeeded
  retries: 3

- name: update pip
  pip:
    name: pip
    state: present
    version: "{{ python_pip_version }}"
  register: update_pip
  until: update_pip is succeeded
  retries: 3

- name: update setuptools
  pip:
    name: setuptools
    state: present
    version: "{{ python_pip_setuptools_version }}"
  register: update_setuptools
  until: update_setuptools is succeeded
  retries: 3

- name: Configure pip proxy
  ini_file:
    path: /etc/pip.conf
    section: global
    option: index-url
    value: "{{ python_pip_proxy }}"
  when:
    - python_pip_proxy is defined

- name: install requested modules
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version | default(omit) }}"
  with_items:
    - "{{ python_pip_modules }}"
  register: install_requested_modules
  until: install_requested_modules is succeeded
  retries: 3
