---
sudo: required
language: python
services: docker

env:
  - version=">=2.7,<2.8" distro="alpine-latest" expectation="fail"
  - version="" distro="alpine-latest" expectation="fail"
  - version="devel" distro="alpine-latest" expectation="fail"
  - version=">=2.7,<2.8" distro="alpine-edge" expectation="fail"
  - version="" distro="alpine-edge" expectation="fail"
  - version="devel" distro="alpine-edge" expectation="fail"
  - version=">=2.7,<2.8" distro="archlinux"
  - version="" distro="archlinux"
  - version="devel" distro="archlinux"
  - version=">=2.7,<2.8" distro="centos-6" expectation="fail"
  - version="" distro="centos-6" expectation="fail"
  - version="devel" distro="centos-6" expectation="fail"
  - version=">=2.7,<2.8" distro="centos-latest" expectation="fail"
  - version="" distro="centos-latest" expectation="fail"
  - version="devel" distro="centos-latest" expectation="fail"
  - version=">=2.7,<2.8" distro="debian-stable" expectation="fail"
  - version="" distro="debian-stable" expectation="fail"
  - version="devel" distro="debian-stable" expectation="fail"
  - version=">=2.7,<2.8" distro="debian-unstable" expectation="fail"
  - version="" distro="debian-unstable" expectation="fail"
  - version="devel" distro="debian-unstable" expectation="fail"
  - version=">=2.7,<2.8" distro="fedora-latest"
  - version="" distro="fedora-latest"
  - version="devel" distro="fedora-latest"
  - version=">=2.7,<2.8" distro="fedora-rawhide"
  - version="" distro="fedora-rawhide"
  - version="devel" distro="fedora-rawhide"
  - version=">=2.7,<2.8" distro="opensuse-leap" expectation="fail"
  - version="" distro="opensuse-leap" expectation="fail"
  - version="devel" distro="opensuse-leap" expectation="fail"
  - version=">=2.7,<2.8" distro="ubuntu-rolling" expectation="fail"
  - version="" distro="ubuntu-rolling" expectation="fail"
  - version="devel" distro="ubuntu-rolling" expectation="fail"
  - version=">=2.7,<2.8" distro="ubuntu-latest" expectation="fail"
  - version="" distro="ubuntu-latest" expectation="fail"
  - version="devel" distro="ubuntu-latest" expectation="fail"
  - version=">=2.7,<2.8" distro="ubuntu-devel" expectation="fail"
  - version="" distro="ubuntu-devel" expectation="fail"
  - version="devel" distro="ubuntu-devel" expectation="fail"

matrix:
  allow_failures:
    - env: version=">=2.7,<2.8" distro="alpine-edge" expectation="fail"
    - env: version="" distro="alpine-edge" expectation="fail"
    - env: version="devel" distro="alpine-edge" expectation="fail"
    - env: version="devel" distro="alpine-latest" expectation="fail"
    - env: version="devel" distro="archlinux"
    - env: version="devel" distro="centos-6" expectation="fail"
    - env: version="devel" distro="centos-latest" expectation="fail"
    - env: version="devel" distro="debian-stable" expectation="fail"
    - env: version=">=2.7,<2.8" distro="debian-unstable" expectation="fail"
    - env: version="" distro="debian-unstable" expectation="fail"
    - env: version="devel" distro="debian-unstable" expectation="fail"
    - env: version="devel" distro="fedora-latest"
    - env: version=">=2.7,<2.8" distro="fedora-rawhide"
    - env: version="" distro="fedora-rawhide"
    - env: version="devel" distro="fedora-rawhide"
    - env: version="devel" distro="opensuse-leap" expectation="fail"
    - env: version="devel" distro="ubuntu-rolling" expectation="fail"
    - env: version=">=2.7,<2.8" distro="ubuntu-devel" expectation="fail"
    - env: version="" distro="ubuntu-devel" expectation="fail"
    - env: version="devel" distro="ubuntu-devel" expectation="fail"
    - env: version="devel" distro="ubuntu-latest" expectation="fail"

cache:
  - pip

install:
  - pip install --upgrade pip
  - if [ "${version}" != "devel" ] ; then pip install ansible"${version}" ; fi
  - if [ "${version}" = "devel" ] ; then pip install git+https://github.com/ansible/ansible.git@devel ; fi
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "KNGb6nUiIFk86AMSfRdnFFWcKh4whVEcvS3ycBdhEBhbG4/4d8TBNFILjLpvTrr5d2Vmhj4JM2dRTwfkEj+ChC9cCknSVwkwZqbOx+H1NmiYgTWHn8Ar89NOh/GnaV3aU1AcK36L+7M9pcoTaLtl0BRWwrR4BUCIUFqgOf7vEtKWew+b1zmaGG3hygrGYFMKFJa4GfsGiSYnkn8TFG2muacgzlActQzML1xHrE/kR4hWK7dMZCLdPDgzXyRDwMZwkQQxPwKe0rCLYY7izzRoFchziyyvtwCrZ2F5sN4HsNploCwBRPCw3o6ZdhybPlmEls/PE+UhshV7NZb8t5/oX2bTHnHABEyRs6dLJotxgYCkkU4brlq2btWiYVP5FdCHYF/PraQbb5yNl+fKGSPimGj++B3MgIGLaq0ZskO3RC+RiqNnO5V6/SLjr4zk4JqPtPl7CEX3o77VcxQQEm91Xk7++yNCng8ShAK2IrBWxezQc4ZwyyvntNYi+ODqJaJDMCE+RQAaw1iBvGgaAX2P798LPJRew9D64xByC7FUKTe9TSOoYG635/iKWVDLneLd3CdvaKwkBSx2A/6eO6HGjSqi7PHhY1Y3Jru+oTVB3NNopHHLNNo2Qv1us76meP6LoxaoCvkt7/YmFkCYxvkCWey5q6vq0Kd0IhC3uGYFSkA="
  email: false
