---
roles:
  - name: robertdebock.bootstrap
  - name: robertdebock.buildtools
  - name: robertdebock.epel
  - name: robertdebock.python_pip
  - name: robertdebock.service
collections:
  - name: community.general
