---
# defaults file for common

# The selected hostname.
common_hostname: "{{ inventory_hostname }}"

# A list of nameservers to configure.
# common_nameservers:
#   - 1.1.1.1
#   - 1.0.0.1

# Fill /etc/hosts with all hosts in the play.
common_hosts: "{{ groups.all }}"

# Do you want to reboot on a hostname change?
common_reboot: yes
