---

- name: test if reboot_always is set correctly
  ansible.builtin.assert:
    that:
      - reboot_always is defined
      - reboot_always is boolean
    quiet: yes

- name: test if reboot_delay is set correctly
  ansible.builtin.assert:
    that:
      - reboot_delay is defined
      - reboot_delay is number
      - reboot_delay >= 0
    quiet: yes

- name: test if reboot_up_delay is set correctly
  ansible.builtin.assert:
    that:
      - reboot_up_delay is defined
      - reboot_up_delay is number
      - reboot_up_delay >= 0
    quiet: yes

- name: test if reboot_message is set correctly
  ansible.builtin.assert:
    that:
      - reboot_message is defined
      - reboot_message is string
    quiet: yes
