---
galaxy_info:
  author: Robert de Bock
  namespace: robertdebock
  role_name: python_pip
  description: Install pythons pip on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: "2.10"

  platforms:
    - name: Alpine
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - python
    - pip
    - pypip
    - system
    - installer

dependencies: []
