---
galaxy_info:
  author: Robert de Bock
  role_name: atom
  description: Install atom on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.8

  platforms:
    - name: Amazon
      versions:
        - Candidate
    - name: Alpine
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - artful
        - bionic

  galaxy_tags:
    - atom
    - archlinux
    - centos
    - rhel

dependencies: []
