---
galaxy_info:
  author: Robert de Bock
  role_name: ansible_lint
  description: Install ansible-lint on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.8

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - 8
    - name: Fedora
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - artful
        - bionic

  galaxy_tags:
    - ansiblelint
    - archlinux
    - centos
    - rhel

dependencies: []
