---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: ec2
platforms:
  - name: docker-rhel-7
    image: ami-c86c3f23
    instance_type: t2.micro
    vpc_subnet_id: subnet-0e688067
  - name: docker-sles-15
    image: ami-0a1886cf45f944eb1
    instance_type: t2.micro
    vpc_subnet_id: subnet-0e688067
  - name: docker-ubuntu-18.04
    image: ami-0bdf93799014acdc4
    instance_type: t2.micro
    vpc_subnet_id: subnet-0e688067
  - name: docker-amazon-linux-2
    image: ami-02ea8f348fa28c108
    instance_type: t2.micro
    vpc_subnet_id: subnet-0e688067
  - name: docker-centos-7
    image: ami-9a183671
    instance_type: t2.micro
    vpc_subnet_id: subnet-0e688067
  - name: docker-fedora-29
    image: ami-0f904cfaa69a1c64c
    instance_type: t2.micro
    vpc_subnet_id: subnet-0e688067
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      docker-ubuntu-18.04:
        ansible_user: ubuntu
      docker-centos-7:
        ansible_user: centos
      docker-fedora-29:
        ansible_user: fedora
scenario:
  name: ec2
  create_sequence:
    - create
  check_sequence:
    - destroy
    - dependency
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
