---
galaxy_info:
  author: Robert de Bock
  role_name: travis
  description: Installs travis on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.8

  platforms:
    - name: Alpine
      versions:
        - all
    - name: EL
      versions:
        - 8
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - bionic
        - xenial

  galaxy_tags:
    - travis
    - centos

dependencies: []
