---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check if port 25 is open
      wait_for:
        port: 25

    - name: check if a mail can be sent
      mail:
        from: "Robert de Bock <robert@example.com>"
        to: "Robert de Bock <root@example.com>"
        subject: Testing ansible-role-postfix.
        body: Testing the ansible role postfix.
