---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: rhel-7
    image: ami-c86c3f23
    instance_type: t2.micro
    vpc_subnet_id: subnet-0e688067
  - name: sles-15
    image: ami-0a1886cf45f944eb1
    instance_type: t2.micro
    vpc_subnet_id: subnet-0e688067
  - name: epel-ubuntu-18.04
    image: ami-0bdf93799014acdc4
    instance_type: t2.micro
    vpc_subnet_id: subnet-0e688067
  - name: epel-amazon-linux-2
    image: ami-02ea8f348fa28c108
    instance_type: t2.micro
    vpc_subnet_id: subnet-0e688067
  - name: epel-centos-7
    image: ami-9a183671
    instance_type: t2.micro
    vpc_subnet_id: subnet-0e688067
  - name: epel-fedora-29
    image: ami-0f904cfaa69a1c64c
    instance_type: t2.micro
    vpc_subnet_id: subnet-0e688067
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      epel-ubuntu-18.04:
        ansible_user: ubuntu
      epel-centos-7:
        ansible_user: centos
      epel-fedora-29:
        ansible_user: fedora
scenario:
  name: ec2
