---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check if atom exists works
      ansible.builtin.stat:
        path: /usr/bin/atom
      register: atom_test_one
      failed_when:
        - not atom_test_one.stat.exists
