---
# vars file for buildroot
_buildtools_packages:
  default:
    - build-essential
  Alpine:
    - alpine-sdk
    - bison
    - elfutils-libelf
    - libffi-dev
    - openssl-dev
    - perl-utils
    - python3-dev
  Archlinux:
    - base-devel
    - libelf
  Debian:
    - bison
    - build-essential
    - libelf-dev
  CentOS-7:
    - "@Development Tools"
    - elfutils-libelf-devel
    - perl-Digest-SHA
    - python-devel
  CentOS:
    - "@Development Tools"
    - elfutils-libelf-devel
    - perl-Digest-SHA
    - python3-devel
  RedHat:
    - bison
    - elfutils-libelf-devel
    - gcc
    - make
    - perl-Digest-SHA
  Suse:
    - bison
    - gcc
    - libelf-devel
    - make
    - perl-Digest-SHA1

buildtools_packages: "{{ _buildtools_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_buildtools_packages[ansible_distribution] | default(_buildtools_packages[ansible_os_family] | default (_buildtools_packages['default']))) }}"
