---
galaxy_info:
  author: Robert de Bock
  namespace: robertdebock
  role_name: postfix
  description: Install and configure postfix on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: "2.10"

  platforms:
    - name: Amazon
      versions:
        - 2018.03
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - installer
    - mailserver
    - package
    - postfix
    - security
    - system

dependencies: []
