---
galaxy_info:
  author: Robert de Bock
  role_name: molecule
  description: Install Molecule on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.8

  platforms:
    - name: Alpine
      versions:
        - all
    - name: EL
      versions:
        - 8
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Fedora
      versions:
        - 31
        - 32
    - name: Ubuntu
      versions:
        - focal

  galaxy_tags:
    - molecule
    - centos

dependencies: []
