---
# vars file for digitalocean-agent
digitalocean_agent_gpgkey: https://repos.sonar.digitalocean.com/sonar-agent.asc

_digitalocean_agent_repository_src:
  default: []
  apt: digitalocean-agent.list
  dnf: digitalocean-agent.repo
  yum: digitalocean-agent.repo

digitalocean_agent_repository_src: "{{ _digitalocean_agent_repository_src[ansible_pkg_mgr] | default(_digitalocean_agent_repository_src['default']) }}"

_digitalocean_agent_repository_dest:
  default: []
  apt: /etc/apt/sources.list.d/digitalocean-agent.list
  dnf: /etc/yum.repos.d/digitalocean-agent.repo
  yum: /etc/yum.repos.d/digitalocean-agent.repo

digitalocean_agent_repository_dest: "{{ _digitalocean_agent_repository_dest[ansible_pkg_mgr] | default(_digitalocean_agent_repository_dest['default']) }}"
