---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ansible_lint-alpine-edge
    image: alpine:edge
    command: sh -c "while true ; do sleep 1 ; done"
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_lint_ignore_docker: no
  lint:
    name: ansible-lint
scenario:
  name: alpine-edge
verifier:
  name: goss
  lint:
    name: yamllint
