---
galaxy_info:
  author: Robert de Bock
  role_name: users
  description: The purpose of this role is to add users and groups on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.6

  platforms:
    - name: Alpine
      versions:
        - all
    - name: ArchLinux
      version:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      version:
        - 6
        - 7
    - name: Fedora
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - artful
        - bionic

  galaxy_tags:
    - users
    - alpine
    - centos
    - debian
    - el
    - fedora
    - opensuse
    - rhel
    - server
    - sudo
    - system
    - ubuntu

dependencies: []
