---
galaxy_info:
  author: Robert de Bock
  role_name: docker
  description: Install and configure Docker (non-CE) on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.8

  platforms:
    - name: Alpine
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all

  galaxy_tags:
    - docker
    - centos
    - rhel

dependencies: []
