---
galaxy_info:
  author: Robert de Bock
  role_name: docker
  description: Install and configure Docker (non-CE) on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: "2.10"

  platforms:
    - name: Alpine
      versions:
        - all
    - name: EL
      versions:
        - 8
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - bionic

  galaxy_tags:
    - docker

dependencies: []
